import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../data/models/project_model.dart';
import '../../data/models/task_model.dart';
import '../../data/models/user_model.dart';
import '../auth/auth.controller.dart';
import '../auth/auth.provider.dart';

class HomeScreen extends ConsumerStatefulWidget { const HomeScreen({super.key}); @override ConsumerState<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends ConsumerState<HomeScreen> {
  Future<List<ProjectModel>>? _projects;
  @override void initState() { super.initState(); _load(); }
  void _load() { final org = ref.read(authControllerProvider).orgId; _projects = ref.read(projectRepositoryProvider).getProjects(org!); }
  @override Widget build(BuildContext context) {
    final auth = ref.watch(authControllerProvider); final isAdmin = auth.role == 'org_admin';
    return Scaffold(
      appBar: AppBar(title: const Text('TaskFlow'), actions: [IconButton(tooltip: 'Refresh', icon: const Icon(Icons.refresh), onPressed: () => setState(_load)), PopupMenuButton<String>(onSelected: (v) { if(v == 'logout') ref.read(authControllerProvider.notifier).logout(); }, itemBuilder: (_) => [const PopupMenuItem(value: 'profile', child: Text('Profile & settings')), const PopupMenuItem(value: 'logout', child: Text('Logout'))])]),
      floatingActionButton: FloatingActionButton.extended(onPressed: () => _projectForm(), icon: const Icon(Icons.add), label: const Text('Project')),
      body: FutureBuilder<List<ProjectModel>>(future: _projects, builder: (context, snapshot) {
        if(snapshot.connectionState != ConnectionState.done) return const Center(child: CircularProgressIndicator());
        if(snapshot.hasError) return _ErrorView(message: '${snapshot.error}', retry: () => setState(_load));
        final items = snapshot.data ?? []; if(items.isEmpty) return const _EmptyView(icon: Icons.folder_off_outlined, text: 'No projects yet');
        return RefreshIndicator(onRefresh: () async => setState(_load), child: ListView.separated(padding: const EdgeInsets.all(16), itemCount: items.length, separatorBuilder: (_, __) => const SizedBox(height: 10), itemBuilder: (context, i) { final project = items[i]; return Card(child: ListTile(contentPadding: const EdgeInsets.all(16), title: Text(project.name, style: const TextStyle(fontWeight: FontWeight.w600)), subtitle: Padding(padding: const EdgeInsets.only(top: 6), child: Text(project.description)), trailing: Column(mainAxisAlignment: MainAxisAlignment.center, children:[Text('${project.taskCount}', style: const TextStyle(fontWeight: FontWeight.bold)), const Text('tasks')]), onTap: () async { await Navigator.push(context, MaterialPageRoute(builder: (_) => ProjectDetailScreen(project: project, orgId: auth.orgId!, isAdmin: isAdmin))); setState(_load); },)); })); }),
    );
  }
  Future<void> _projectForm() async { final name = TextEditingController(); final description = TextEditingController(); final form = GlobalKey<FormState>(); final result = await showDialog<bool>(context: context, builder: (ctx) => AlertDialog(title: const Text('New project'), content: Form(key: form, child: Column(mainAxisSize: MainAxisSize.min, children:[TextFormField(controller:name, decoration:const InputDecoration(labelText:'Name'), validator:(v)=>v == null || v.trim().isEmpty ? 'Name is required' : null), TextFormField(controller:description, decoration:const InputDecoration(labelText:'Description'), minLines:2, maxLines:3)])), actions:[TextButton(onPressed:()=>Navigator.pop(ctx), child:const Text('Cancel')), FilledButton(onPressed:() async {if(form.currentState!.validate()) {await ref.read(projectRepositoryProvider).createProject(orgId:ref.read(authControllerProvider).orgId!,name:name.text.trim(),description:description.text.trim()); if(ctx.mounted) Navigator.pop(ctx,true);}},child:const Text('Create'))])); if(result == true && mounted) setState(_load); name.dispose(); description.dispose(); }
}

class ProjectDetailScreen extends ConsumerStatefulWidget { const ProjectDetailScreen({super.key, required this.project, required this.orgId, required this.isAdmin}); final ProjectModel project; final String orgId; final bool isAdmin; @override ConsumerState<ProjectDetailScreen> createState()=>_ProjectDetailScreenState(); }
class _ProjectDetailScreenState extends ConsumerState<ProjectDetailScreen> { Future<List<TaskModel>>? _tasks; String? _status; String? _priority; @override void initState(){super.initState();_load();} void _load()=>_tasks=ref.read(taskRepositoryProvider).getTasks(widget.project.id);
  @override Widget build(BuildContext context) => Scaffold(appBar:AppBar(title:Text(widget.project.name), actions:[if(widget.isAdmin) IconButton(icon:const Icon(Icons.delete_outline), onPressed:_deleteProject)]), floatingActionButton:FloatingActionButton.extended(onPressed: _taskForm, icon:const Icon(Icons.add_task), label:const Text('Task')), body:FutureBuilder<List<TaskModel>>(future:_tasks,builder:(context,snapshot){if(snapshot.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return _ErrorView(message:'${snapshot.error}',retry:()=>setState(_load));var tasks=snapshot.data??[];tasks=tasks.where((t)=>(_status==null||t.status==_status)&&(_priority==null||t.priority==_priority)).toList();return RefreshIndicator(onRefresh:()async=>setState(_load),child:ListView(padding:const EdgeInsets.all(16),children:[_Summary(tasks:snapshot.data??[]),const SizedBox(height:16),Wrap(spacing:8,children:[_filter('Status',_status,['todo','in_progress','review','done'],(v)=>setState(()=>_status=v)),_filter('Priority',_priority,['low','medium','high','urgent'],(v)=>setState(()=>_priority=v))]),const SizedBox(height:8),if(tasks.isEmpty)const Padding(padding:EdgeInsets.only(top:56),child:_EmptyView(icon:Icons.task_alt,text:'No tasks match these filters')),...tasks.map((task)=>_TaskCard(task:task,onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>TaskDetailScreen(task:task,orgId:widget.orgId))).then((_)=>setState(_load))))]));}));
  Widget _filter(String label,String? current,List<String> values,ValueChanged<String?> changed)=>DropdownButton<String>(hint:Text(label),value:current,items:[const DropdownMenuItem(value:null,child:Text('All')), ...values.map((x)=>DropdownMenuItem(value:x,child:Text(x.replaceAll('_',' '))) )],onChanged:changed);
  Future<void> _deleteProject() async { final ok=await _confirm(context,'Delete project?','This cannot be undone.');if(ok){try{await ref.read(projectRepositoryProvider).deleteProject(projectId:widget.project.id,isAdmin:widget.isAdmin);if(mounted)Navigator.pop(context);}catch(e){if(mounted)_snack(context,'$e');}}}
  Future<void> _taskForm() async { final title=TextEditingController();final description=TextEditingController();String priority='medium';final form=GlobalKey<FormState>();final result=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('New task'),content:Form(key:form,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:title,decoration:const InputDecoration(labelText:'Title'),validator:(v)=>v==null||v.trim().isEmpty?'Title is required':null),TextFormField(controller:description,decoration:const InputDecoration(labelText:'Description')),StatefulBuilder(builder:(c,set)=>DropdownButtonFormField(value:priority,decoration:const InputDecoration(labelText:'Priority'),items:['low','medium','high','urgent'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>priority=v!)))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()async{if(form.currentState!.validate()){await ref.read(taskRepositoryProvider).createTask(projectId:widget.project.id,title:title.text.trim(),description:description.text.trim(),priority:priority);if(ctx.mounted)Navigator.pop(ctx,true);}},child:const Text('Create'))]));title.dispose();description.dispose();if(result==true&&mounted)setState(_load);}
}

class TaskDetailScreen extends ConsumerStatefulWidget {const TaskDetailScreen({super.key,required this.task,required this.orgId});final TaskModel task;final String orgId;@override ConsumerState<TaskDetailScreen> createState()=>_TaskDetailScreenState();}
class _TaskDetailScreenState extends ConsumerState<TaskDetailScreen>{late TaskModel task;Future<List<UserModel>>? members;@override void initState(){super.initState();task=widget.task;members=ref.read(taskRepositoryProvider).getOrgMembers(widget.orgId);}Future<void> _save(TaskModel next)async{await ref.read(taskRepositoryProvider).updateTask(next);setState(()=>task=next);}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Task details'),actions:[IconButton(icon:const Icon(Icons.delete_outline),onPressed:_delete)]),body:ListView(padding:const EdgeInsets.all(20),children:[Text(task.title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),Text(task.description.isEmpty?'No description':task.description),const SizedBox(height:24),_choice('Status',task.status,['todo','in_progress','review','done'],(v)=>_save(task.copyWith(status:v))),_choice('Priority',task.priority,['low','medium','high','urgent'],(v)=>_save(task.copyWith(priority:v))),FutureBuilder<List<UserModel>>(future:members,builder:(context,snapshot){final users=snapshot.data??[];return DropdownButtonFormField<String>(value:task.assigneeId,decoration:const InputDecoration(labelText:'Assignee'),items:[const DropdownMenuItem(value:null,child:Text('Unassigned')),...users.map((u)=>DropdownMenuItem(value:u.id,child:Text(u.name)))],onChanged:(id)async{try{await ref.read(taskRepositoryProvider).assignTask(taskId:task.id,userId:id,orgId:widget.orgId);setState(()=>task=task.copyWith(assigneeId:id,clearAssignee:id==null));}catch(e){if(mounted)_snack(context,'$e');}});}),const SizedBox(height:20),Text('Due ${DateFormat.yMMMd().format(task.dueDate)}',style:Theme.of(context).textTheme.bodyMedium)]));
Widget _choice(String label,String value,List<String> values,ValueChanged<String> changed)=>Padding(padding:const EdgeInsets.only(bottom:16),child:DropdownButtonFormField(value:value,decoration:InputDecoration(labelText:label),items:values.map((x)=>DropdownMenuItem(value:x,child:Text(x.replaceAll('_',' ')))).toList(),onChanged:(v){if(v!=null)changed(v);}));Future<void>_delete()async{if(await _confirm(context,'Delete task?','This cannot be undone.')){await ref.read(taskRepositoryProvider).deleteTask(task.id);if(mounted)Navigator.pop(context);}}}

class _Summary extends StatelessWidget {const _Summary({required this.tasks});final List<TaskModel> tasks;@override Widget build(BuildContext context){final counts={for(final s in ['todo','in_progress','review','done'])s:tasks.where((t)=>t.status==s).length};return Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:counts.entries.map((e)=>Column(children:[Text('${e.value}',style:Theme.of(context).textTheme.titleLarge),Text(e.key.replaceAll('_',' '))])).toList())));}}
class _TaskCard extends StatelessWidget{const _TaskCard({required this.task,required this.onTap});final TaskModel task;final VoidCallback onTap;@override Widget build(BuildContext context)=>Card(child:ListTile(onTap:onTap,title:Text(task.title),subtitle:Text('${task.status.replaceAll('_',' ')} • ${task.priority} • due ${DateFormat.MMMd().format(task.dueDate)}'),trailing:const Icon(Icons.chevron_right)));}
class _EmptyView extends StatelessWidget{const _EmptyView({required this.icon,required this.text});final IconData icon;final String text;@override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:48,color:Theme.of(context).colorScheme.outline),const SizedBox(height:12),Text(text)]));}
class _ErrorView extends StatelessWidget{const _ErrorView({required this.message,required this.retry});final String message;final VoidCallback retry;@override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Could not load data: $message',textAlign:TextAlign.center),const SizedBox(height:12),OutlinedButton(onPressed:retry,child:const Text('Retry'))]));}
Future<bool>_confirm(BuildContext context,String title,String body)=>showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(title),content:Text(body),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))])).then((v)=>v??false);void _snack(BuildContext c,String text)=>ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(text)));
